### ISSUE TITLE
about AttributeError: 'NoneType' object has no attribute 'params'

### ISSUE THREAD

**Issue by chengchengcode** [kartheikiyer/dense_basis#3]
Hi Kartheik,

Thank you very much for sharing this code. I am trying to learn how to use it follow the example here: https://dense-basis.readthedocs.io/en/latest/tutorials/getting_started.html, and got stuck in this step:

fname = 'test_atlas'
N_pregrid = 1000
priors.Nparam = 3
db.generate_atlas(N_pregrid = N_pregrid,priors = priors, fname = fname, store=True,filter_list = filter_list, filt_dir = filt_dir) 

Here are the message I got. Could you help me about this issue?

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-f2ae69a1fc5e> in <module>()
      4 
      5 db.generate_atlas(N_pregrid = N_pregrid,priors = priors,fname = fname,
----> 6                   store=True,filter_list = filter_list, filt_dir = filt_dir)
      7 

~/anaconda3/lib/python3.6/site-packages/dense_basis-0.1.4-py3.6.egg/dense_basis/pre_grid.py in generate_atlas(N_pregrid, priors, initial_seed, store, filter_list, filt_dir, norm_method, z_step, sp, cosmology, fname, path)
    302     Nparam = priors.Nparam
    303     rand_sfh_tuple, rand_Z, rand_Av, rand_z = priors.sample_all_params_safesSFR(random_seed = initial_seed)
--> 304     _, lam = make_spec(rand_sfh_tuple, rand_Z, rand_Av, rand_z, igmval = True, return_lam = True, sp = mocksp, cosmology = cosmo)
    305 
    306     fc_zgrid = np.arange(priors.z_min-z_step, priors.z_max+z_step, z_step)

~/anaconda3/lib/python3.6/site-packages/dense_basis-0.1.4-py3.6.egg/dense_basis/pre_grid.py in make_spec(sfh_tuple, metval, dustval, zval, igmval, return_lam, return_ms, sp, cosmology)
     66         """
     67 
---> 68     sp.params['add_igm_absorption'] = igmval
     69     sp.params['zred'] = zval
     70     sfh, timeax = tuple_to_sfh(sfh_tuple, zval = zval)

AttributeError: 'NoneType' object has no attribute 'params'

**Comment by kartheikiyer** [comment]
Hi Cheng, this looks like an issue involving [python-FSPS](http://dfm.io/python-fsps/current/stellarpop_api/#api-reference), which is a prerequisite package for dense_basis. Could you try running the following piece of code involving only the FSPS package:

```
import fsps
sp = fsps.StellarPopulation(compute_vega_mags=False, zcontinuous=1,
                                sfh=0, logzsol=0.0, dust_type=2, dust2=0.2)

sp.params["imf_type"] = 1
sp.params["logzsol"] = -0.3
```

If this runs fine, then I'll look further into this issue. Otherwise you can probably fix this by (re)installing FSPS.

**Comment by chengchengcode** [comment]
Hi Kartheik,

Thank you very much for your help and sorry for my late reply. I was not be able to get on line for several days.

I found the previous problem is caused by my fsps. Now I install the fsps follow this page: http://dfm.io/python-fsps/current/installation/ and the code you sent to me:

import fsps
sp = fsps.StellarPopulation(compute_vega_mags=False, zcontinuous=1,
                                sfh=0, logzsol=0.0, dust_type=2, dust2=0.2)

sp.params["imf_type"] = 1
sp.params["logzsol"] = -0.3

runs well.

Then I run:

fname = 'test_atlas'
N_pregrid = 1000
priors.Nparam = 3
db.generate_atlas(N_pregrid = N_pregrid,
                  priors = priors,
                  fname = fname, store=True,
                  filter_list = filter_list, filt_dir = filt_dir)

I got new error like this:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-3c41535da931> in <module>()
      5                   priors = priors,
      6                   fname = fname, store=True,
----> 7                   filter_list = filter_list, filt_dir = filt_dir)

~/anaconda3/lib/python3.6/site-packages/dense_basis-0.1.4-py3.6.egg/dense_basis/pre_grid.py in generate_atlas(N_pregrid, priors, initial_seed, store, filter_list, filt_dir, norm_method, z_step, sp, cosmology, fname, path)
    302     Nparam = priors.Nparam
    303     rand_sfh_tuple, rand_Z, rand_Av, rand_z = priors.sample_all_params_safesSFR(random_seed = initial_seed)
--> 304     _, lam = make_spec(rand_sfh_tuple, rand_Z, rand_Av, rand_z, igmval = True, return_lam = True, sp = mocksp, cosmology = cosmo)
    305 
    306     fc_zgrid = np.arange(priors.z_min-z_step, priors.z_max+z_step, z_step)

~/anaconda3/lib/python3.6/site-packages/dense_basis-0.1.4-py3.6.egg/dense_basis/pre_grid.py in make_spec(sfh_tuple, metval, dustval, zval, igmval, return_lam, return_ms, sp, cosmology)
     71     timeax = timeax
     72     sp.params['sfh'] = 3
---> 73     sp.set_tabular_sfh(timeax, sfh)
     74     sp.params['cloudy_dust'] = True
     75     sp.params['dust_type'] = 2

AttributeError: 'StellarPopulation' object has no attribute 'set_tabular_sfh'

Could you help me with this error?

Best,
Cheng

**Comment by kartheikiyer** [comment]
Hi Cheng, I'm glad that worked. I suspect that the new error you're seeing is also likely a python-fsps issue - if you've installed it using pypi, it installs version 0.2.2, but (I think) the set_tabular_sfh() function wasn't implemented until a later version. You can check this by doing 
```
import fsps
print(fsps.__version__)
```
if this is < 0.3.0, you might want to uninstall python-fsps, and then reinstall by cloning the latest version of the repository from https://github.com/dfm/python-fsps/ instead of using a pip install.

**Comment by chengchengcode** [comment]
Hi Kartheik,

Thank you very much for your help! the fsps is indeed 0.2.2. Now I use the new version, and the example works very well! Thanks!

Best,
Cheng

**Comment by kartheikiyer** [comment]
Great. Since that solved the problem, I'm closing this issue. .)
